project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "MUSA 550"
  page-footer:
    left: "delmelle@gmail.com"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."

  sidebar:
    logo: "images/course-icon.png"
    pinned: true
    align: center
    tools:
      - icon: globe
        href: https://www.design.upenn.edu/people/eric-delmelle
        text: "Personal Website"
      - icon: github
        href: https://github.com/MUSA-550-Fall-2024/
        text: "MUSA 550 GitHub"
      - icon: twitter
        href: https://twitter.com/ericdelmelle
        text: "Eric Delmelle Twitter"
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - about.qmd
      - section: analysis/index.qmd
        contents:
          - Untitled-1.ipynb

format:
  html:
    highlight-style: solarized
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true
